include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    constant_identifier_names: false
    prefer_single_quotes: true
    use_build_context_synchronously: false
    depend_on_referenced_packages: false
    library_private_types_in_public_api: false